apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
    release: "0-5"
  type: NodePort
  ports:
    - name: http
      port: 80
      # targetPort: 80
      nodePort: 30080

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
    release: "1"
  type: NodePort
  ports:
    - name: http
      port: 8161
      # targetPort: 80
      nodePort: 30010